### ISSUE TITLE
It does not work with QGIS: 3.34.10-Prizren Prizren, 113de9e1 

### ISSUE THREAD

**Issue by BaBoWaGa** [planetfederal/qgis-milstd2525-plugin#18]
Si è verificato un errore durante l'esecuzione del codice Python: 

TypeError: QgsMarkerSymbolLayer.setSizeUnit(): argument 1 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins\milstd2525\renderer.py", line 162, in createRendererWidget
    return MilStd2525RendererWidget(layer, style, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins\milstd2525\renderer.py", line 128, in __init__
    self.r = MilStd2525Renderer(field=field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins\milstd2525\renderer.py", line 54, in __init__
    self._defaultSymbol = getDefaultSymbol(int(size))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins\milstd2525\milstd2525symbology.py", line 134, in getDefaultSymbol
    symbolLayer.setSizeUnit(3)
TypeError: QgsMarkerSymbolLayer.setSizeUnit(): argument 1 has unexpected type 'int'

Versione Python: 3.12.5 (main, Aug  8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)] 
Versione di QGIS: 3.34.10-Prizren Prizren, 113de9e1 

Percorso Python:
C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins\lftools
C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins\aino-qgis-plugin-main
C:/PROGRA~1/QGIS33~1.10/apps/qgis-ltr/./python
C:/Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python
C:/Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python/plugins
C:/PROGRA~1/QGIS33~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.10\apps\grass\grass84\etc\python
C:\Users\gianl\Documents
C:\Program Files\QGIS 3.34.10\bin\python312.zip
C:\PROGRA~1\QGIS33~1.10\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib
C:\Program Files\QGIS 3.34.10\bin
C:\PROGRA~1\QGIS33~1.10\apps\Python312
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.10\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\BaBoWaGa/python
C:\Users\gianl\AppData\Roaming\QGIS\QGIS3\profiles\BaBoWaGa\python\plugins\HCMGIS/forms
C:\Users\gianl\AppData\Roaming\QGIS\QGIS3\profiles\BaBoWaGa\python\plugins\milstd2525\extlibs
.
C:/Users/gianl/Documents/OSINT World/osintworld.net/server/qgiscloud

**Comment by RiiPiii** [comment]
1. goto Settings -> User profiles -> Open Active Profile Folder
2. find in folder ...\python\plugins\milstd2525\milstd2525symbology.py file
3. add to code after line 35 "**from qgis.core import QgsUnitTypes  # Import the correct enumeration type**"
4. edit in code rows 120 and 134 "_symbolLayer.setSizeUnit(3)_" to "_**symbolLayer.setSizeUnit(QgsUnitTypes.RenderPixels)**_"

restart QGIS, and it should work again

**Comment by BaBoWaGa** [comment]
> 1. goto Settings -> User profiles -> Open Active Profile Folder
> 2. find in folder ...\python\plugins\milstd2525\milstd2525symbology.py file
> 3. add to code after line 35 "**from qgis.core import QgsUnitTypes  # Import the correct enumeration type**"
> 4. edit in code rows 120 and 134 "_symbolLayer.setSizeUnit(3)_" to "_**symbolLayer.setSizeUnit(QgsUnitTypes.RenderPixels)**_"
> 
> restart QGIS, and it should work again

Well now it works thank you.
Do you know if there will be future updates with APP-6 symbols?
